# base
FROM python:3.7.3-slim-stretch as base 

# create app directory
WORKDIR /app

# install poetry
RUN pip install poetry==0.12.16

# copy poetry files to app directory
COPY poetry.lock pyproject.toml /app/

# install dependencies
RUN poetry config settings.virtualenvs.create false
RUN poetry install --no-interaction

# copy project files
COPY . /app

ENTRYPOINT python3 backend.py
